#!/usr/bin/env python3

"""
# CubePostprocessor

Just a post processor make life easier with Cube 2 from 3DSystems.

Support KISSlicer 1.5b, Cura 15.04.04 and Slic3r 1.2.9.

With all slicer g-code, it cleans the file after processing (removes comments and extra lines, makes sure EOL is Windows)

With KISS
 - allows for solid and infill extrusion amount tuning

With Cura
 - change first layer temp 10 C higher than rest of the print

With Slicer
 - converts Makerware (Makerbot) style g-code to Cube (BfB) format

Disclaimer: i'm not responsible if anything, good or bad, happens due to use of this script.

Version 0.7
"""


import logging
import os
import platform
import subprocess
import sys
import argparse

from CubePostprocessor.slicer_cura import CuraPrintFile
from CubePostprocessor.slicer_kisslicer import KissPrintFile
from CubePostprocessor.slicer_simplify3d import Simplify3dPrintFile
from CubePostprocessor.slicer_slic3r import Slic3rPrintFile
from CubePostprocessor import utils

fmt = logging.Formatter(fmt="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
filehandler = logging.FileHandler("process.log")
filehandler.setFormatter(fmt)
streamhandler = logging.StreamHandler(stream=sys.stdout)
streamhandler.setFormatter(fmt)
log = logging.getLogger("Cubifier")
log.setLevel(logging.INFO)
log.addHandler(filehandler)
log.addHandler(streamhandler)


def detect_file_type(gcode_file):
    with open(gcode_file, 'r') as gf:
        line1 = gf.readline()
        if line1.startswith('; KISSlicer'):
            log.info("Detected KISSlicer format")
            return KissPrintFile
        elif line1.startswith('; CURA'):
            log.info("Detected Cura format")
            return CuraPrintFile
        elif line1.startswith('; generated by Slic3r'):
            log.info("Detected Slic3r format")
            return Slic3rPrintFile
        elif line1.startswith('; G-Code generated by Simplify3D(R)'):
            log.info("Detected Simplify3D format")
            return Simplify3dPrintFile
        else:
            log.error("No supported gcode file detected. Is comments enabled on Kisslicer or '; CURA' header added to Cura start.gcode?")
            exit(1)

def run_cube_utils(intermediary_file, keep_intermediary = False):
    # Check to make sure CodeX64.exe was installed properly
    _dir, fname = os.path.split(intermediary_file)
    name, ext = os.path.splitext(fname)
    cube_file = os.path.join(_dir,  name + ".cube")

    codex_args = ["cubepro-encoder",
        intermediary_file,
        cube_file]
    subprocess.call(codex_args)
    log.info("Wrote new file: {}".format(cube_file))

    if not keep_intermediary:
        os.remove(intermediary_file)
        log.info("Removed intermediatry file: {}".format(intermediary_file))
    return

def main():
    parser = argparse.ArgumentParser(description='Postprocess bfb files for Cube 2')
    parser.add_argument('-k', '--keep', action='store_true', help = 'keep intermediary bfb file')
    parser.add_argument('-d', '--debug', action='store_true', help = 'enable debugging mode')
    parser.add_argument('filename')
    args = parser.parse_args()

    if(args.debug):
        print(args)

    print_type = detect_file_type(args.filename)
    pf = print_type(debug=args.debug)
    result_file = pf.process(args.filename)
    run_cube_utils(result_file, args.keep)


if __name__ == "__main__":
    main()
